language: node_js
node_js:
  - "8.7"
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
script:
  - echo Hello World && sleep 30 && exit 1
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
